// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם סוֹפְרִים 5!', start: 0.0, end: 4.776, words: [] },
  { text: 'חֲמִשָּׁה', start: 6.367, end: 7.327, words: [], units: [{ g: 'חֲמִשָּׁה', start: 6.727, end: 7.327 }] },
  { text: 'אֶחָד', start: 8.667, end: 10.683, words: [] },
  { text: 'שְׁנַיִם', start: 12.0, end: 14.184, words: [] },
  { text: 'שְׁלוֹשָׁה', start: 15.333, end: 17.325, words: [] },
  { text: 'אַרְבָּעָה', start: 18.666, end: 20.682, words: [] },
  { text: 'חֲמִשָּׁה', start: 21.999, end: 24.159, words: [] },
  { text: 'אַתֶּם!', start: 25.332, end: 27.444, words: [] },
];
