import React from 'react';
import { ReadingShort } from '../../lib/reading-render';
import beats from '../../../../reading-shorts/read-2-patach/beats.json';
import { VO } from './vo.gen';

// AUTO-GENERATED by tools/make_reading.py — registration stub only. Never hand-edit.
// The generic ReadingShort renders any mode:reading beats.json; this file exists so
// gen-registry has a stable compositionConfig.id + durationInSeconds per video.
export const compositionConfig = {
  id: 'Read2Patach',
  durationInSeconds: 31.645,
  fps: 30,
  width: 1080,
  height: 1920,
};
const Read2Patach: React.FC = () => <ReadingShort beats={beats} vo={VO} />;
export default Read2Patach;
