// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים פַּתָּח! אוֹתוֹ צְלִיל כְּמוֹ קָמָץ!', start: 0.0, end: 7.632, words: [] },
  { text: 'בַּ', start: 9.7, end: 10.28, words: [], units: [{ g: 'בַּ', start: 10.0, end: 10.28 }] },
  { text: 'בַּ מַּ גַּ דַּ', start: 11.9, end: 16.19, words: [], units: [{ g: 'בַּ', start: 12.2, end: 12.48 }, { g: 'מַּ', start: 13.33, end: 13.63 }, { g: 'גַּ', start: 14.5, end: 14.92 }, { g: 'דַּ', start: 15.79, end: 16.19 }] },
  { text: 'דַּדַּ', start: 17.7, end: 21.492, words: [], units: [{ g: 'דַּ', start: 18.02, end: 18.42 }, { g: 'דַּ', start: 19.916, end: 20.316 }] },
  { text: 'גַּם!', start: 23.7, end: 25.692, words: [] },
  { text: 'אַתֶּם!', start: 27.033, end: 29.145, words: [] },
];
