import React from 'react';
import { LearnShort } from '../../lib/learn-render';
import beats from '../../../../number-shorts/number-add-2-2/beats.json';
import { VO } from './vo.gen';

// AUTO-GENERATED by tools/make_learn.py — registration stub only. Never hand-edit.
// The generic LearnShort renders any mode:number beats.json; this file exists so
// gen-registry has a stable compositionConfig.id + durationInSeconds per video.
export const compositionConfig = {
  id: 'NumberAdd22',
  durationInSeconds: 26.611,
  fps: 30,
  width: 1080,
  height: 1920,
};
const NumberAdd22: React.FC = () => <LearnShort beats={beats} vo={VO} />;
export default NumberAdd22;
