// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בָּ', start: 1.0, end: 1.58, words: [], units: [{ g: 'בָּ', start: 1.3, end: 1.58 }] },
  { text: 'בָּבָּא', start: 4.0, end: 5.848, words: [] },
];
