// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים שֵׁם עֶצֶם אוֹ פּוֹעַל!', start: 0.0, end: 5.424, words: [] },
  { text: 'שֵׁם עֶצֶם אוֹ פּוֹעַל', start: 8.867, end: 10.287, words: [], units: [{ g: 'שֵׁם עֶצֶם אוֹ פּוֹעַל', start: 9.167, end: 10.287 }] },
  { text: 'בַּיִת', start: 11.167, end: 13.255, words: [] },
  { text: 'רָץ', start: 14.5, end: 16.54, words: [] },
  { text: 'כֶּלֶב', start: 17.833, end: 19.849, words: [] },
  { text: 'אוֹכֵל', start: 21.166, end: 23.11, words: [] },
  { text: 'סֵפֶר', start: 24.499, end: 26.611, words: [] },
  { text: 'יָשֵׁן', start: 27.832, end: 29.872, words: [] },
  { text: 'אַתֶּם!', start: 31.165, end: 33.277, words: [] },
];
