import React from 'react';
import { LearnShort } from '../../lib/learn-render';
import beats from '../../../../wordclass-shorts/wordclass-3-nouns-vs-verbs/beats.json';
import { VO } from './vo.gen';

// AUTO-GENERATED by tools/make_learn.py — registration stub only. Never hand-edit.
// The generic LearnShort renders any mode:wordclass beats.json; this file exists so
// gen-registry has a stable compositionConfig.id + durationInSeconds per video.
export const compositionConfig = {
  id: 'Wordclass3NounsVsVerbs',
  durationInSeconds: 35.777,
  fps: 30,
  width: 1080,
  height: 1920,
};
const Wordclass3NounsVsVerbs: React.FC = () => <LearnShort beats={beats} vo={VO} />;
export default Wordclass3NounsVsVerbs;
