import React from 'react';
import { ReadingShort } from '../../lib/reading-render';
import beats from '../../../../reading-shorts/read-9-kubutz/beats.json';
import { VO } from './vo.gen';

// AUTO-GENERATED by tools/make_learn.py — registration stub only. Never hand-edit.
// The generic ReadingShort renders any mode:reading beats.json; this file exists so
// gen-registry has a stable compositionConfig.id + durationInSeconds per video.
export const compositionConfig = {
  id: 'Read9Kubutz',
  durationInSeconds: 29.645,
  fps: 30,
  width: 1080,
  height: 1920,
};
const Read9Kubutz: React.FC = () => <ReadingShort beats={beats} vo={VO} />;
export default Read9Kubutz;
