// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים קֻבּוּץ! אוֹתוֹ צְלִיל כְּמוֹ שׁוּרוּק!', start: 0.0, end: 7.632, words: [] },
  { text: 'בֻּ', start: 9.7, end: 10.32, words: [], units: [{ g: 'בֻּ', start: 10.0, end: 10.32 }] },
  { text: 'בֻּ דֻ לֻ סֻ', start: 11.9, end: 16.19, words: [], units: [{ g: 'בֻּ', start: 12.2, end: 12.52 }, { g: 'דֻ', start: 13.37, end: 13.71 }, { g: 'לֻ', start: 14.6, end: 14.92 }, { g: 'סֻ', start: 15.83, end: 16.19 }] },
  { text: 'תֻּת', start: 17.7, end: 19.596, words: [], units: [{ g: 'תֻּת', start: 18.06, end: 18.3 }] },
  { text: 'תֻּת!', start: 21.7, end: 23.62, words: [] },
  { text: 'אַתֶּם!', start: 25.033, end: 27.145, words: [] },
];
