// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים אֶת הָאוֹת הֵי!', start: 0.0, end: 4.776, words: [] },
  { text: 'ה', start: 8.033, end: 8.653, words: [], units: [{ g: 'ה', start: 8.493, end: 8.653 }] },
  { text: 'הָר', start: 10.333, end: 12.277, words: [] },
  { text: 'הֵד', start: 13.666, end: 15.61, words: [] },
  { text: 'הוֹד', start: 16.999, end: 18.943, words: [] },
  { text: 'אַתֶּם!', start: 20.332, end: 22.444, words: [] },
];
