// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים אֶת הָאוֹת דָּלֶת!', start: 0.0, end: 5.136, words: [] },
  { text: 'ד', start: 8.033, end: 8.833, words: [], units: [{ g: 'ד', start: 8.333, end: 8.833 }] },
  { text: 'דֶּלֶת', start: 10.333, end: 12.469, words: [] },
  { text: 'דָּג', start: 13.666, end: 15.658, words: [] },
  { text: 'דְּלִי', start: 16.999, end: 18.895, words: [] },
  { text: 'אַתֶּם!', start: 20.332, end: 22.444, words: [] },
];
