// AUTO-GENERATED by tools/gen_voice_edge.py — do not edit.
// Word times are REAL Edge-TTS word boundaries; captions sync exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! שָׁלוֹם, יְלָדִים וִילָדוֹת!', start: 0.0, end: 4.8, words: [{ w: 'בּוּ', start: 0.1, end: 0.426 }, { w: 'בּוּ', start: 0.426, end: 0.806 }, { w: 'שָׁלוֹם', start: 1.739, end: 2.486 }, { w: 'יְלָדִים', start: 2.745, end: 3.22 }, { w: 'וִילָדוֹת', start: 3.22, end: 3.913 }] },
  { text: 'זוֹהִי הָאוֹת א.', start: 5.0, end: 7.47, words: [{ w: 'זוֹהִי', start: 5.104, end: 5.58 }, { w: 'הָאוֹת', start: 5.58, end: 5.906 }, { w: 'א', start: 5.906, end: 6.585 }] },
  { text: 'מָה מַתְחִיל בְּאוֹת א?', start: 9.0, end: 11.55, words: [{ w: 'מָה', start: 9.101, end: 9.318 }, { w: 'מַתְחִיל', start: 9.318, end: 9.712 }, { w: 'בְּאוֹת', start: 9.713, end: 9.984 }, { w: 'א', start: 9.984, end: 10.65 }] },
  { text: 'הִמְהוּם…', start: 12.0, end: 13.87, words: [{ w: 'הִמְהוּם', start: 12.1, end: 12.97 }] },
  { text: 'תַּפּוּחַ! אָדוֹם וּמָתוֹק!', start: 14.5, end: 18.43, words: [{ w: 'תַּפּוּחַ', start: 14.625, end: 15.498 }, { w: 'אָדוֹם', start: 16.36, end: 16.834 }, { w: 'וּמָתוֹק', start: 16.834, end: 17.58 }] },
  { text: 'וְגַם אֶפְרוֹחַ! קְטַן־קְטַן!', start: 18.5, end: 22.68, words: [{ w: 'וְגַם', start: 18.604, end: 18.998 }, { w: 'אֶפְרוֹחַ', start: 18.998, end: 19.8 }, { w: 'קְטַן־קְטַן', start: 20.742, end: 21.788 }] },
  { text: 'אוֹת א, אוֹת א — אֶפְשָׁר לְהַמְשִׁיךְ!', start: 23.0, end: 27.63, words: [{ w: 'אוֹת', start: 23.118, end: 23.349 }, { w: 'א', start: 23.349, end: 24.042 }, { w: 'אוֹת', start: 24.273, end: 24.531 }, { w: 'א', start: 24.531, end: 25.183 }, { w: 'אֶפְשָׁר', start: 25.55, end: 25.93 }, { w: 'לְהַמְשִׁיךְ', start: 25.93, end: 26.746 }] },
  { text: 'אֲבָל הַיּוֹם, הָאוֹת א עוֹשָׂה אוֹתְךָ!', start: 28.0, end: 31.6, words: [{ w: 'אֲבָל', start: 28.1, end: 28.467 }, { w: 'הַיּוֹם', start: 28.467, end: 29.037 }, { w: 'הָאוֹת', start: 29.282, end: 29.635 }, { w: 'א', start: 29.635, end: 29.975 }, { w: 'עוֹשָׂה', start: 29.975, end: 30.233 }, { w: 'אוֹתְךָ', start: 30.233, end: 30.695 }] },
  { text: 'בּוּ בּוּ — אוֹהֵב אוֹתְךָ!', start: 32.0, end: 34.79, words: [{ w: 'בּוּ', start: 32.132, end: 32.335 }, { w: 'בּוּ', start: 32.335, end: 32.784 }, { w: 'אוֹהֵב', start: 33.069, end: 33.422 }, { w: 'אוֹתְךָ', start: 33.422, end: 33.898 }] },
];
