// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים שְׁוָוא! הַנְּקֻדָּה הַשּׁוֹקַעַת!', start: 0.0, end: 7.368, words: [] },
  { text: 'בְּ', start: 8.033, end: 8.653, words: [], units: [{ g: 'בְּ', start: 8.333, end: 8.653 }] },
  { text: 'בְּ דְ לְ מְ', start: 10.233, end: 14.683, words: [], units: [{ g: 'בְּ', start: 10.533, end: 10.853 }, { g: 'דְ', start: 11.703, end: 12.203 }, { g: 'לְ', start: 13.093, end: 13.373 }, { g: 'מְ', start: 14.243, end: 14.683 }] },
  { text: 'דְּלִי', start: 16.033, end: 19.609, words: [], units: [{ g: 'דְּ', start: 16.333, end: 16.653 }, { g: 'לִי', start: 18.173, end: 18.453 }] },
  { text: 'דְּלִי!', start: 22.033, end: 23.977, words: [] },
  { text: 'אַתֶּם!', start: 25.366, end: 27.478, words: [] },
];
