import React from 'react';
import { LearnShort } from '../../lib/learn-render';
import beats from '../../../../letter-shorts/letter-6-vav/beats.json';
import { VO } from './vo.gen';

// AUTO-GENERATED by tools/make_learn.py — registration stub only. Never hand-edit.
// The generic LearnShort renders any mode:letter beats.json; this file exists so
// gen-registry has a stable compositionConfig.id + durationInSeconds per video.
export const compositionConfig = {
  id: 'Letter6Vav',
  durationInSeconds: 24.944,
  fps: 30,
  width: 1080,
  height: 1920,
};
const Letter6Vav: React.FC = () => <LearnShort beats={beats} vo={VO} />;
export default Letter6Vav;
