// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים אֶת הָאוֹת וָו!', start: 0.0, end: 4.944, words: [] },
  { text: 'ו', start: 8.033, end: 8.673, words: [], units: [{ g: 'ו', start: 8.333, end: 8.673 }] },
  { text: 'וָרֹד', start: 10.333, end: 12.397, words: [] },
  { text: 'וֶרֶד', start: 13.666, end: 15.73, words: [] },
  { text: 'וִילוֹן', start: 16.999, end: 19.087, words: [] },
  { text: 'אַתֶּם!', start: 20.332, end: 22.444, words: [] },
];
