// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'שָׁלוֹם יְלָדִים, כֵּיף שֶׁחֲזַרְתֶּם! הַיּוֹם לוֹמְדִים נִיקּוּד חָדָשׁ — קָמָץ!', start: 0.0, end: 8.376, words: [] },
  { text: 'אָ', start: 10.533, end: 11.033, words: [], units: [{ g: 'אָ', start: 10.833, end: 11.033 }] },
  { text: 'אָ-בָּא', start: 12.733, end: 16.141, words: [], units: [{ g: 'אָ', start: 13.033, end: 13.233 }, { g: 'בָּא', start: 14.665, end: 14.965 }] },
  { text: 'אָ-רוֹן', start: 18.633, end: 22.209, words: [], units: [{ g: 'אָ', start: 18.933, end: 19.133 }, { g: 'רוֹן', start: 20.605, end: 21.065 }] },
  { text: 'אָ-דוֹם', start: 24.533, end: 28.133, words: [], units: [{ g: 'אָ', start: 24.833, end: 25.033 }, { g: 'דוֹם', start: 26.465, end: 26.965 }] },
  { text: 'אָ-רוּחַ', start: 30.433, end: 35.689, words: [], units: [{ g: 'אָ', start: 30.733, end: 30.933 }, { g: 'רוּ', start: 32.385, end: 32.705 }, { g: 'חַ', start: 34.261, end: 34.501 }] },
  { text: 'אָ-מָּן', start: 38.333, end: 41.909, words: [], units: [{ g: 'אָ', start: 38.633, end: 38.833 }, { g: 'מָּן', start: 40.285, end: 40.685 }] },
  { text: 'אַבָּא', start: 44.333, end: 46.133, words: [] },
  { text: 'אָרוֹן', start: 47.666, end: 49.658, words: [] },
  { text: 'אָדוֹם', start: 50.999, end: 52.967, words: [] },
  { text: 'אֲרוּחָה', start: 54.332, end: 56.372, words: [] },
  { text: 'אֻמָּן', start: 57.665, end: 59.705, words: [] },
  { text: 'כָּל הַכָּבוֹד יְלָדִים, לְמַדְתֶּם מְצֻיָּין! נִמְשִׁיךְ לִלְמֹד בַּפֶּרֶק הַבָּא. לְהִתְרָאוֹת!', start: 60.998, end: 69.542, words: [] },
];
