// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים אֶת הָאוֹת בֵּית!', start: 0.0, end: 5.064, words: [] },
  { text: 'בּ', start: 8.033, end: 8.653, words: [], units: [{ g: 'בּ', start: 8.333, end: 8.653 }] },
  { text: 'בֵּית', start: 10.333, end: 12.397, words: [] },
  { text: 'בַּד', start: 13.666, end: 15.634, words: [] },
  { text: 'בֹּקֶר', start: 16.999, end: 19.015, words: [] },
  { text: 'אַתֶּם!', start: 20.332, end: 22.444, words: [] },
];
