// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים שֵׁם עֶצֶם!', start: 0.0, end: 4.872, words: [] },
  { text: 'שֵׁם עֶצֶם', start: 7.2, end: 8.32, words: [], units: [{ g: 'שֵׁם עֶצֶם', start: 7.58, end: 8.32 }] },
  { text: 'בַּיִת', start: 9.5, end: 11.588, words: [] },
  { text: 'כֶּלֶב', start: 12.833, end: 14.849, words: [] },
  { text: 'חָתוּל', start: 16.166, end: 18.23, words: [] },
  { text: 'סֵפֶר', start: 19.499, end: 21.611, words: [] },
  { text: 'פֶּרַח', start: 22.832, end: 24.896, words: [] },
  { text: 'אַתֶּם!', start: 26.165, end: 28.277, words: [] },
];
