// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים אֶת הָאוֹת גִּימֶל!', start: 0.0, end: 5.136, words: [] },
  { text: 'ג', start: 8.033, end: 8.933, words: [], units: [{ g: 'ג', start: 8.353, end: 8.933 }] },
  { text: 'גַּם', start: 10.333, end: 12.325, words: [] },
  { text: 'גֶּשֶׁם', start: 13.666, end: 15.85, words: [] },
  { text: 'גָּדוֹל', start: 16.999, end: 19.159, words: [] },
  { text: 'אַתֶּם!', start: 20.332, end: 22.444, words: [] },
];
