// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים אֶת הָאוֹת חֵית!', start: 0.0, end: 5.016, words: [] },
  { text: 'ח', start: 8.033, end: 8.693, words: [], units: [{ g: 'ח', start: 8.433, end: 8.693 }] },
  { text: 'חַג', start: 10.333, end: 12.349, words: [] },
  { text: 'חָלָב', start: 13.666, end: 15.778, words: [] },
  { text: 'חֶדֶר', start: 16.999, end: 19.063, words: [] },
  { text: 'אַתֶּם!', start: 20.332, end: 22.444, words: [] },
];
