import React from 'react';
import { ReadingShort } from '../../lib/reading-render';
import beats from '../../../../reading-shorts/read-6-chirik/beats.json';
import { VO } from './vo.gen';

// AUTO-GENERATED by tools/make_learn.py — registration stub only. Never hand-edit.
// The generic ReadingShort renders any learn beats.json; this file exists so
// gen-registry has a stable compositionConfig.id + durationInSeconds per video.
export const compositionConfig = {
  id: 'Read6Chirik',
  durationInSeconds: 27.978,
  fps: 30,
  width: 1080,
  height: 1920,
};
const Read6Chirik: React.FC = () => <ReadingShort beats={beats} vo={VO} />;
export default Read6Chirik;
