// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים חִירִיק! הַצְּלִיל "אִי"!', start: 0.0, end: 7.152, words: [] },
  { text: 'בִּ', start: 8.033, end: 8.653, words: [], units: [{ g: 'בִּ', start: 8.333, end: 8.653 }] },
  { text: 'בִּ דִ לִ מִ', start: 10.233, end: 14.423, words: [], units: [{ g: 'בִּ', start: 10.533, end: 10.853 }, { g: 'דִ', start: 11.703, end: 12.023 }, { g: 'לִ', start: 12.893, end: 13.213 }, { g: 'מִ', start: 14.083, end: 14.423 }] },
  { text: 'פִּיל', start: 16.033, end: 17.809, words: [], units: [{ g: 'פִּיל', start: 16.333, end: 16.673 }] },
  { text: 'פִּיל!', start: 20.033, end: 21.833, words: [] },
  { text: 'אַתֶּם!', start: 23.366, end: 25.478, words: [] },
];
