import React from 'react';
import { LearnShort } from '../../lib/learn-render';
import beats from '../../../../number-shorts/number-7-seven/beats.json';
import { VO } from './vo.gen';

// AUTO-GENERATED by tools/make_learn.py — registration stub only. Never hand-edit.
// The generic LearnShort renders any mode:number beats.json; this file exists so
// gen-registry has a stable compositionConfig.id + durationInSeconds per video.
export const compositionConfig = {
  id: 'Number7Seven',
  durationInSeconds: 36.61,
  fps: 30,
  width: 1080,
  height: 1920,
};
const Number7Seven: React.FC = () => <LearnShort beats={beats} vo={VO} />;
export default Number7Seven;
