// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'שָׁלוֹם יְלָדִים, כֵּיף שֶׁחֲזַרְתֶּם! הַיּוֹם לוֹמְדִים נִיקּוּד חָדָשׁ — קָמָץ!', start: 0.0, end: 8.376, words: [] },
  { text: 'אָ', start: 10.533, end: 11.033, words: [], units: [{ g: 'אָ', start: 10.833, end: 11.033 }] },
  { text: 'בָּ מָּ קָּ', start: 12.733, end: 15.713, words: [], units: [{ g: 'בָּ', start: 13.033, end: 13.313 }, { g: 'מָּ', start: 14.163, end: 14.463 }, { g: 'קָּ', start: 15.453, end: 15.713 }] },
  { text: 'מָמָא', start: 17.333, end: 20.885, words: [], units: [{ g: 'מָ', start: 17.633, end: 17.933 }, { g: 'מָא', start: 19.409, end: 19.709 }] },
  { text: 'בָּבָּא', start: 23.233, end: 26.785, words: [], units: [{ g: 'בָּ', start: 23.533, end: 23.813 }, { g: 'בָּא', start: 25.309, end: 25.609 }] },
  { text: 'אַבָּא', start: 29.133, end: 32.685, words: [], units: [{ g: 'אַ', start: 29.433, end: 29.633 }, { g: 'בָּא', start: 31.209, end: 31.509 }] },
  { text: 'מָמָא', start: 35.133, end: 36.981, words: [] },
  { text: 'בָּבָּא', start: 38.466, end: 40.314, words: [] },
  { text: 'אַבָּא', start: 41.799, end: 43.599, words: [] },
  { text: 'כָּל הַכָּבוֹד יְלָדִים, לָמַדְתֶּם אֶת הַקָּמָץ! הִמְהוּם… לְהִתְרָאוֹת!', start: 45.132, end: 53.964, words: [] },
];
