// AUTO-GENERATED by tools/gen_voice_edge.py — do not edit.
// Word times are REAL Edge-TTS word boundaries; captions sync exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'מתקפת בקמטוטים סביב העיניים?', start: 0.4, end: 3.03, words: [{ w: 'מתקפת', start: 0.508, end: 0.905 }, { w: 'בקמטוטים', start: 0.906, end: 1.457 }, { w: 'סביב', start: 1.457, end: 1.711 }, { w: 'העיניים', start: 1.711, end: 2.307 }] },
  { text: 'החודש בלבד: 249 שקל במקום 350.', start: 3.1, end: 7.53, words: [{ w: 'החודש', start: 3.19, end: 3.538 }, { w: 'בלבד', start: 3.538, end: 4.059 }, { w: '249', start: 4.274, end: 5.205 }, { w: 'שקל', start: 5.205, end: 5.522 }, { w: 'במקום', start: 5.522, end: 5.87 }, { w: '350', start: 5.87, end: 6.852 }] },
  { text: 'אבחון עור אישי ופרוטוקול מדויק. תוצאות שרואים.', start: 7.3, end: 11.64, words: [{ w: 'אבחון', start: 7.377, end: 7.827 }, { w: 'עור', start: 7.827, end: 8.052 }, { w: 'אישי', start: 8.052, end: 8.348 }, { w: 'ופרוטוקול', start: 8.348, end: 8.788 }, { w: 'מדויק', start: 8.788, end: 9.362 }, { w: 'תוצאות', start: 10.062, end: 10.43 }, { w: 'שרואים', start: 10.43, end: 10.962 }] },
  { text: 'אז בואי להזמין תור בוואטסאפ.', start: 11.2, end: 14.3, words: [{ w: 'אז', start: 11.301, end: 11.567 }, { w: 'בואי', start: 11.567, end: 11.846 }, { w: 'להזמין', start: 11.846, end: 12.365 }, { w: 'תור', start: 12.365, end: 12.604 }, { w: 'בוואטסאפ', start: 12.604, end: 13.428 }] },
];
