// AUTO-GENERATED by tools/gen_voice_edge.py — do not edit.
// Word times are REAL Edge-TTS word boundaries; captions sync exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'נמאס לשלם?', start: 0.0, end: 2.02, words: [{ w: 'נמאס', start: 0.13, end: 0.489 }, { w: 'לשלם?', start: 0.489, end: 1.14 }] },
  { text: 'סטודיו נועה.', start: 2.5, end: 4.66, words: [{ w: 'סטודיו', start: 2.603, end: 3.188 }, { w: 'נועה.', start: 3.188, end: 3.787 }] },
  { text: 'תספורת + פן במחיר השקה', start: 5.0, end: 7.88, words: [{ w: 'תספורת', start: 5.085, end: 5.815 }, { w: '+', start: 5.815, end: 6.074 }, { w: 'פן', start: 6.074, end: 6.322 }, { w: 'במחיר', start: 6.322, end: 6.647 }, { w: 'השקה', start: 6.647, end: 7.141 }] },
  { text: 'המחיר כולל עיצוב מלא — בלי הפתעות בקופה.', start: 7.95, end: 11.94, words: [{ w: 'הַמְּחִיר', start: 8.04, end: 8.503 }, { w: 'כּוֹלֵל', start: 8.503, end: 8.824 }, { w: 'עִיצּוּב', start: 8.824, end: 9.157 }, { w: 'מָלֵא', start: 9.157, end: 9.584 }, { w: 'בְּלִי', start: 9.846, end: 10.072 }, { w: 'הַפְתָּעוֹת', start: 10.072, end: 10.523 }, { w: 'בַּקֻּופָּה', start: 10.523, end: 11.153 }] },
  { text: 'קבעי תור.', start: 12.01, end: 14.08, words: [{ w: 'קבעי', start: 12.127, end: 12.579 }, { w: 'תור.', start: 12.579, end: 13.204 }] },
];
