// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם סוֹפְרִים 8!', start: 0.0, end: 4.632, words: [] },
  { text: 'שְׁמֹנָה', start: 6.367, end: 7.247, words: [], units: [{ g: 'שְׁמֹנָה', start: 6.787, end: 7.247 }] },
  { text: 'אֶחָד', start: 8.667, end: 10.683, words: [] },
  { text: 'שְׁנַיִם', start: 12.0, end: 14.184, words: [] },
  { text: 'שְׁלוֹשָׁה', start: 15.333, end: 17.325, words: [] },
  { text: 'אַרְבָּעָה', start: 18.666, end: 20.682, words: [] },
  { text: 'חֲמִשָּׁה', start: 21.999, end: 24.159, words: [] },
  { text: 'שִׁשָּׁה', start: 25.332, end: 27.324, words: [] },
  { text: 'שִׁבְעָה', start: 28.665, end: 30.705, words: [] },
  { text: 'שְׁמֹנָה', start: 31.998, end: 34.038, words: [] },
  { text: 'אַתֶּם!', start: 35.331, end: 37.443, words: [] },
];
