// AUTO-GENERATED by tools/gen_voice_edge.py — do not edit.
// Word times are REAL Edge-TTS word boundaries; captions sync exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'מספיק לחפש קוסמטיקאית.', start: 0.0, end: 2.33, words: [{ w: 'מספיק', start: 0.115, end: 0.445 }, { w: 'לחפש', start: 0.445, end: 0.83 }, { w: 'קוסמטיקאית', start: 0.83, end: 1.63 }] },
  { text: 'החודש: 199 שקל במקום 290.', start: 2.4, end: 6.93, words: [{ w: 'החודש', start: 2.509, end: 3.279 }, { w: '199', start: 3.515, end: 4.471 }, { w: 'שקל', start: 4.471, end: 4.831 }, { w: 'במקום', start: 4.831, end: 5.191 }, { w: '290', start: 5.191, end: 6.11 }] },
  { text: 'אבחון עור אישי. תוצאות שרואים.', start: 7.0, end: 10.33, words: [{ w: 'אבחון', start: 7.101, end: 7.485 }, { w: 'עור', start: 7.485, end: 7.671 }, { w: 'אישי', start: 7.671, end: 8.035 }, { w: 'תוצאות', start: 8.742, end: 9.116 }, { w: 'שרואים', start: 9.116, end: 9.654 }] },
  { text: 'הזמינו תור עכשיו בוואטסאפ.', start: 10.4, end: 13.35, words: [{ w: 'הזמינו', start: 10.517, end: 11.022 }, { w: 'תור', start: 11.022, end: 11.261 }, { w: 'עכשיו', start: 11.261, end: 11.647 }, { w: 'בוואטסאפ', start: 11.647, end: 12.471 }] },
];
