// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים אֶת הָאוֹת אָלֶף!', start: 0.0, end: 5.208, words: [] },
  { text: 'א', start: 8.033, end: 8.693, words: [], units: [{ g: 'א', start: 8.413, end: 8.693 }] },
  { text: 'אַבָּא', start: 10.333, end: 12.133, words: [] },
  { text: 'אֲנִי', start: 13.666, end: 15.466, words: [] },
  { text: 'אֹרֶן', start: 16.999, end: 19.015, words: [] },
  { text: 'אַתֶּם!', start: 20.332, end: 22.444, words: [] },
];
