// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים חוֹלָם! הַצְּלִיל "אוֹ"!', start: 0.0, end: 6.96, words: [] },
  { text: 'בֹּ', start: 8.033, end: 8.673, words: [], units: [{ g: 'בֹּ', start: 8.333, end: 8.673 }] },
  { text: 'בֹּ לֹ מֹ רֹ', start: 10.233, end: 14.443, words: [], units: [{ g: 'בֹּ', start: 10.533, end: 10.873 }, { g: 'לֹ', start: 11.743, end: 12.063 }, { g: 'מֹ', start: 12.913, end: 13.253 }, { g: 'רֹ', start: 14.123, end: 14.443 }] },
  { text: 'טוֹב', start: 16.033, end: 17.929, words: [], units: [{ g: 'טוֹב', start: 16.413, end: 16.633 }] },
  { text: 'טוֹב!', start: 20.033, end: 21.929, words: [] },
  { text: 'אַתֶּם!', start: 23.366, end: 25.478, words: [] },
];
