// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים אֶת הָאוֹת זַיִן!', start: 0.0, end: 5.016, words: [] },
  { text: 'ז', start: 8.033, end: 8.953, words: [], units: [{ g: 'ז', start: 8.353, end: 8.953 }] },
  { text: 'זָהָב', start: 10.333, end: 12.421, words: [] },
  { text: 'זְמַן', start: 13.666, end: 15.682, words: [] },
  { text: 'זֶבְרָה', start: 16.999, end: 19.015, words: [] },
  { text: 'אַתֶּם!', start: 20.332, end: 22.444, words: [] },
];
