// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים דָּגֵשׁ קַל! בּ/ב, כּ/כ, פּ/פ!', start: 0.0, end: 9.96, words: [] },
  { text: 'בּ', start: 10.46, end: 11.08, words: [], units: [{ g: 'בּ', start: 10.76, end: 11.08 }] },
  { text: 'בּ כּ פּ', start: 11.9, end: 14.78, words: [], units: [{ g: 'בּ', start: 12.2, end: 12.52 }, { g: 'כּ', start: 13.55, end: 13.69 }, { g: 'פּ', start: 14.6, end: 14.78 }] },
  { text: 'בֹּקֶר', start: 16.5, end: 20.196, words: [], units: [{ g: 'בֹּ', start: 16.8, end: 17.14 }, { g: 'קֶר', start: 18.72, end: 19.06 }] },
  { text: 'בֹּקֶר!', start: 22.5, end: 24.516, words: [] },
  { text: 'אַתֶּם!', start: 25.833, end: 27.945, words: [] },
];
