// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם סוֹפְרִים 4!', start: 0.0, end: 4.56, words: [] },
  { text: 'אַרְבָּעָה', start: 6.367, end: 7.227, words: [], units: [{ g: 'אַרְבָּעָה', start: 6.707, end: 7.227 }] },
  { text: 'אֶחָד', start: 8.667, end: 10.683, words: [] },
  { text: 'שְׁנַיִם', start: 12.0, end: 14.184, words: [] },
  { text: 'שְׁלוֹשָׁה', start: 15.333, end: 17.325, words: [] },
  { text: 'אַרְבָּעָה', start: 18.666, end: 20.682, words: [] },
  { text: 'אַתֶּם!', start: 21.999, end: 24.111, words: [] },
];
