// AUTO-GENERATED by tools/gen_voice_edge.py — do not edit.
// Word times are REAL Edge-TTS word boundaries; captions sync exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'צריך לחתום על מסמך דחוף?', start: 0.5, end: 3.63, words: [{ w: 'צריך', start: 0.602, end: 1.0 }, { w: 'לחתום', start: 1.001, end: 1.493 }, { w: 'על', start: 1.493, end: 1.639 }, { w: 'מסמך', start: 1.639, end: 2.078 }, { w: 'דחוף', start: 2.078, end: 2.782 }] },
  { text: 'בלי מדפסת. בלי סריקה. בלי ריצה לדואר.', start: 4.2, end: 9.19, words: [{ w: 'בלי', start: 4.285, end: 4.581 }, { w: 'מדפסת', start: 4.581, end: 5.363 }, { w: 'בלי', start: 6.126, end: 6.399 }, { w: 'סריקה', start: 6.399, end: 6.989 }, { w: 'בלי', start: 7.751, end: 8.034 }, { w: 'ריצה', start: 8.034, end: 8.351 }, { w: 'לדואר', start: 8.351, end: 8.976 }] },
  { text: 'רושם חותם בעשרים שניות. חוקי ובטוח.', start: 9.8, end: 14.11, words: [{ w: 'רושם', start: 9.886, end: 10.288 }, { w: 'חותם', start: 10.288, end: 10.713 }, { w: 'בעשרים', start: 10.713, end: 11.126 }, { w: 'שניות', start: 11.126, end: 11.77 }, { w: 'חוקי', start: 12.544, end: 13.049 }, { w: 'ובטוח', start: 13.049, end: 13.875 }] },
];
