// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים פּוֹעַל!', start: 0.0, end: 4.608, words: [] },
  { text: 'פּוֹעַל', start: 6.367, end: 6.947, words: [], units: [{ g: 'פּוֹעַל', start: 6.627, end: 6.947 }] },
  { text: 'רָץ', start: 8.667, end: 10.707, words: [] },
  { text: 'אוֹכֵל', start: 12.0, end: 13.944, words: [] },
  { text: 'יָשֵׁן', start: 15.333, end: 17.373, words: [] },
  { text: 'שָׁר', start: 18.666, end: 20.658, words: [] },
  { text: 'קוֹפֵץ', start: 21.999, end: 24.159, words: [] },
  { text: 'אַתֶּם!', start: 25.332, end: 27.444, words: [] },
];
