// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם סוֹפְרִים 1!', start: 0.0, end: 4.656, words: [] },
  { text: 'אֶחָד', start: 6.367, end: 7.167, words: [], units: [{ g: 'אֶחָד', start: 6.687, end: 7.167 }] },
  { text: 'אֶחָד', start: 8.667, end: 10.683, words: [] },
  { text: 'אַתֶּם!', start: 12.0, end: 14.112, words: [] },
];
