// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם סוֹפְרִים 1+1!', start: 0.0, end: 5.376, words: [] },
  { text: 'שְׁנַיִם', start: 6.367, end: 7.347, words: [], units: [{ g: 'שְׁנַיִם', start: 6.747, end: 7.347 }] },
  { text: 'אֶחָד', start: 8.667, end: 10.683, words: [] },
  { text: 'שְׁנַיִם', start: 12.0, end: 14.184, words: [] },
  { text: 'אַתֶּם!', start: 15.333, end: 17.445, words: [] },
];
