// AUTO-GENERATED by tools/gen_voice.py — do not edit.
// Word times are the REAL ElevenLabs alignment; captions sync exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'These three words rebuilt a small shop.', start: 0.5, end: 3.39, words: [{ w: 'These', start: 0.874, end: 1.098 }, { w: 'three', start: 1.098, end: 1.322 }, { w: 'words', start: 1.322, end: 1.745 }, { w: 'rebuilt', start: 1.745, end: 2.056 }, { w: 'a', start: 2.056, end: 2.131 }, { w: 'small', start: 2.131, end: 2.455 }, { w: 'shop.', start: 2.455, end: 3.29 }] },
  { text: 'SMOKE-EDITED: seven lemons for a single token.', start: 3.44, end: 6.43, words: [{ w: 'SMOKE-EDITED:', start: 3.748, end: 4.575 }, { w: 'seven', start: 4.575, end: 4.863 }, { w: 'lemons', start: 4.863, end: 5.171 }, { w: 'for', start: 5.171, end: 5.257 }, { w: 'a', start: 5.257, end: 5.334 }, { w: 'single', start: 5.334, end: 5.594 }, { w: 'token.', start: 5.594, end: 6.344 }] },
  { text: 'You can say it back in one breath.', start: 6.38, end: 8.82, words: [{ w: 'You', start: 6.755, end: 6.843 }, { w: 'can', start: 6.843, end: 6.993 }, { w: 'say', start: 6.993, end: 7.192 }, { w: 'it', start: 7.192, end: 7.28 }, { w: 'back', start: 7.28, end: 7.543 }, { w: 'in', start: 7.543, end: 7.63 }, { w: 'one', start: 7.63, end: 7.855 }, { w: 'breath.', start: 7.855, end: 8.73 }] },
];
