// AUTO-GENERATED by tools/gen_voice_edge.py — do not edit.
// Word times are REAL Edge-TTS word boundaries; captions sync exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'חתימה דיגיטלית בחינם.', start: 0.0, end: 2.54, words: [{ w: 'חתימה', start: 0.083, end: 0.611 }, { w: 'דיגיטלית', start: 0.611, end: 1.183 }, { w: 'בחינם', start: 1.183, end: 1.808 }] },
  { text: 'פורמי. פלטפורמת הטפסים של ישראל.', start: 2.6, end: 6.28, words: [{ w: 'פורמי', start: 2.677, end: 3.25 }, { w: 'פלטפורמת', start: 3.938, end: 4.469 }, { w: 'הטפסים', start: 4.469, end: 4.899 }, { w: 'של', start: 4.899, end: 5.032 }, { w: 'ישראל', start: 5.032, end: 5.605 }] },
  { text: 'בונים טופס בעברית בכמה לחיצות.', start: 6.3, end: 9.83, words: [{ w: 'בונים', start: 6.395, end: 6.819 }, { w: 'טופס', start: 6.819, end: 7.353 }, { w: 'בעברית', start: 7.354, end: 7.914 }, { w: 'בכמה', start: 7.914, end: 8.25 }, { w: 'לחיצות', start: 8.25, end: 9.009 }] },
  { text: 'חתימה דיגיטלית חוקית. עם שרשרת ראיות.', start: 9.9, end: 14.15, words: [{ w: 'חתימה', start: 9.978, end: 10.489 }, { w: 'דיגיטלית', start: 10.489, end: 10.981 }, { w: 'חוקית', start: 10.981, end: 11.533 }, { w: 'עם', start: 12.219, end: 12.424 }, { w: 'שרשרת', start: 12.424, end: 12.895 }, { w: 'ראיות', start: 12.895, end: 13.468 }] },
  { text: 'התחילו עכשיו. בלי כרטיס אשראי.', start: 14.1, end: 18.63, words: [{ w: 'התחילו', start: 14.197, end: 14.753 }, { w: 'עכשיו', start: 14.753, end: 15.451 }, { w: 'בלי', start: 16.322, end: 16.645 }, { w: 'כרטיס', start: 16.645, end: 17.136 }, { w: 'אשראי', start: 17.136, end: 17.77 }] },
];
