// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit.
import type React from 'react';
import Shot0, { compositionConfig as cfg0, defaultProps as dp0, calculateMetadata as cm0 } from './shots/ad-1/Ad1Liat';
import Shot1, { compositionConfig as cfg1, defaultProps as dp1, calculateMetadata as cm1 } from './shots/ad-2/Ad2Noa';
import Shot2, { compositionConfig as cfg2, defaultProps as dp2, calculateMetadata as cm2 } from './shots/ad-3/Ad3Formy';
import Shot3, { compositionConfig as cfg3 } from './shots/ad-5/Ad5NoaStudio';
import Shot4, { compositionConfig as cfg4 } from './shots/ai-1/Ai1Door';
import Shot5, { compositionConfig as cfg5, defaultProps as dp5, calculateMetadata as cm5 } from './shots/ai-1/AiSpec';
import Shot6, { compositionConfig as cfg6, defaultProps as dp6, calculateMetadata as cm6 } from './shots/avatar-spec/AvatarSpec';
import Shot7, { compositionConfig as cfg7 } from './shots/letter-1/Letter1Alef';
import Shot8, { compositionConfig as cfg8 } from './shots/letter-2/Letter2Bet';
import Shot9, { compositionConfig as cfg9 } from './shots/letter-3/Letter3Gimel';
import Shot10, { compositionConfig as cfg10 } from './shots/letter-4/Letter4Dalet';
import Shot11, { compositionConfig as cfg11 } from './shots/letter-5/Letter5He';
import Shot12, { compositionConfig as cfg12 } from './shots/letter-6/Letter6Vav';
import Shot13, { compositionConfig as cfg13 } from './shots/letter-7/Letter7Zayin';
import Shot14, { compositionConfig as cfg14 } from './shots/letter-8/Letter8Chet';
import Shot15, { compositionConfig as cfg15 } from './shots/proof-1-lottie/Proof1Lottie';
import Shot16, { compositionConfig as cfg16 } from './shots/proof-2-sketch/Proof2Sketch';
import Shot17, { compositionConfig as cfg17 } from './shots/proof-3-captions/Proof3Captions';
import Shot18, { compositionConfig as cfg18 } from './shots/proof-4-icons/Proof4Icons';
import Shot19, { compositionConfig as cfg19 } from './shots/proof-5-morph/Proof5Morph';
import Shot20, { compositionConfig as cfg20 } from './shots/proof-6-paper/Proof6Paper';
import Shot21, { compositionConfig as cfg21 } from './shots/read-0-test/Read0Test';
import Shot22, { compositionConfig as cfg22 } from './shots/read-10/Read10Shva';
import Shot23, { compositionConfig as cfg23 } from './shots/read-11/Read11DageshKal';
import Shot24, { compositionConfig as cfg24 } from './shots/read-1/Read1Kamatz';
import Shot25, { compositionConfig as cfg25 } from './shots/read-2/Read2Patach';
import Shot26, { compositionConfig as cfg26 } from './shots/read-3/Read3KamatzAba';
import Shot27, { compositionConfig as cfg27 } from './shots/read-4/Read4KamatzAba';
import Shot28, { compositionConfig as cfg28 } from './shots/read-5/Read5TzereSegol';
import Shot29, { compositionConfig as cfg29 } from './shots/read-6/Read6Chirik';
import Shot30, { compositionConfig as cfg30 } from './shots/read-7/Read7Cholam';
import Shot31, { compositionConfig as cfg31 } from './shots/read-8/Read8Shuruk';
import Shot32, { compositionConfig as cfg32 } from './shots/read-9/Read9Kubutz';
import Shot33, { compositionConfig as cfg33 } from './shots/short-10/Short10Fees';
import Shot34, { compositionConfig as cfg34 } from './shots/short-11/Short11Map';
import Shot35, { compositionConfig as cfg35 } from './shots/short-12/Short12Orbit';
import Shot36, { compositionConfig as cfg36 } from './shots/short-13/Short13DadDaughter';
import Shot37, { compositionConfig as cfg37 } from './shots/short-14/Short14TwoEnvelopes';
import Shot38, { compositionConfig as cfg38 } from './shots/short-15/Short15Traffic';
import Shot39, { compositionConfig as cfg39, defaultProps as dp39, calculateMetadata as cm39 } from './shots/short-16/Short16Formy';
import Shot40, { compositionConfig as cfg40 } from './shots/short-17/Short17Sign';
import Shot41, { compositionConfig as cfg41 } from './shots/short-18/Short18BuAleph';
import Shot42, { compositionConfig as cfg42 } from './shots/short-19/Short19KamatzGan';
import Shot43, { compositionConfig as cfg43, defaultProps as dp43, calculateMetadata as cm43 } from './shots/short-1/Short1Chess';
import Shot44, { compositionConfig as cfg44 } from './shots/short-20-karaoke/Short20Karaoke';
import Shot45, { compositionConfig as cfg45 } from './shots/short-2/Short2Math';
import Shot46, { compositionConfig as cfg46 } from './shots/short-3/Short3Algo';
import Shot47, { compositionConfig as cfg47 } from './shots/short-4/Short4Reflog';
import Shot48, { compositionConfig as cfg48 } from './shots/short-5/Short5Monty';
import Shot49, { compositionConfig as cfg49 } from './shots/short-6/Short6Sheet';
import Shot50, { compositionConfig as cfg50 } from './shots/short-7/Short7Kids';
import Shot51, { compositionConfig as cfg51 } from './shots/short-8/Short8Phish';
import Shot52, { compositionConfig as cfg52 } from './shots/short-9/Short9Chords';
import Shot53, { compositionConfig as cfg53 } from './shots/vox-1/Vox1Coffee';
import Shot54, { compositionConfig as cfg54 } from './shots/vox-2/Vox2DadDaughter';
import Shot55, { compositionConfig as cfg55 } from './shots/vox-3/Vox3DorSever';
import Shot56, { compositionConfig as cfg56, defaultProps as dp56, calculateMetadata as cm56 } from './shots/vox-spec/VoxSpec';
import Shot57, { compositionConfig as cfg57 } from './shots/wordclass-1/Wordclass1Nouns';

export const shots: { Comp: React.FC; config: any; defaultProps?: any; calculateMetadata?: any }[] = [
  { Comp: Shot0 as React.FC, config: cfg0, defaultProps: dp0, calculateMetadata: cm0 },
  { Comp: Shot1 as React.FC, config: cfg1, defaultProps: dp1, calculateMetadata: cm1 },
  { Comp: Shot2 as React.FC, config: cfg2, defaultProps: dp2, calculateMetadata: cm2 },
  { Comp: Shot3 as React.FC, config: cfg3 },
  { Comp: Shot4 as React.FC, config: cfg4 },
  { Comp: Shot5 as React.FC, config: cfg5, defaultProps: dp5, calculateMetadata: cm5 },
  { Comp: Shot6 as React.FC, config: cfg6, defaultProps: dp6, calculateMetadata: cm6 },
  { Comp: Shot7 as React.FC, config: cfg7 },
  { Comp: Shot8 as React.FC, config: cfg8 },
  { Comp: Shot9 as React.FC, config: cfg9 },
  { Comp: Shot10 as React.FC, config: cfg10 },
  { Comp: Shot11 as React.FC, config: cfg11 },
  { Comp: Shot12 as React.FC, config: cfg12 },
  { Comp: Shot13 as React.FC, config: cfg13 },
  { Comp: Shot14 as React.FC, config: cfg14 },
  { Comp: Shot15 as React.FC, config: cfg15 },
  { Comp: Shot16 as React.FC, config: cfg16 },
  { Comp: Shot17 as React.FC, config: cfg17 },
  { Comp: Shot18 as React.FC, config: cfg18 },
  { Comp: Shot19 as React.FC, config: cfg19 },
  { Comp: Shot20 as React.FC, config: cfg20 },
  { Comp: Shot21 as React.FC, config: cfg21 },
  { Comp: Shot22 as React.FC, config: cfg22 },
  { Comp: Shot23 as React.FC, config: cfg23 },
  { Comp: Shot24 as React.FC, config: cfg24 },
  { Comp: Shot25 as React.FC, config: cfg25 },
  { Comp: Shot26 as React.FC, config: cfg26 },
  { Comp: Shot27 as React.FC, config: cfg27 },
  { Comp: Shot28 as React.FC, config: cfg28 },
  { Comp: Shot29 as React.FC, config: cfg29 },
  { Comp: Shot30 as React.FC, config: cfg30 },
  { Comp: Shot31 as React.FC, config: cfg31 },
  { Comp: Shot32 as React.FC, config: cfg32 },
  { Comp: Shot33 as React.FC, config: cfg33 },
  { Comp: Shot34 as React.FC, config: cfg34 },
  { Comp: Shot35 as React.FC, config: cfg35 },
  { Comp: Shot36 as React.FC, config: cfg36 },
  { Comp: Shot37 as React.FC, config: cfg37 },
  { Comp: Shot38 as React.FC, config: cfg38 },
  { Comp: Shot39 as React.FC, config: cfg39, defaultProps: dp39, calculateMetadata: cm39 },
  { Comp: Shot40 as React.FC, config: cfg40 },
  { Comp: Shot41 as React.FC, config: cfg41 },
  { Comp: Shot42 as React.FC, config: cfg42 },
  { Comp: Shot43 as React.FC, config: cfg43, defaultProps: dp43, calculateMetadata: cm43 },
  { Comp: Shot44 as React.FC, config: cfg44 },
  { Comp: Shot45 as React.FC, config: cfg45 },
  { Comp: Shot46 as React.FC, config: cfg46 },
  { Comp: Shot47 as React.FC, config: cfg47 },
  { Comp: Shot48 as React.FC, config: cfg48 },
  { Comp: Shot49 as React.FC, config: cfg49 },
  { Comp: Shot50 as React.FC, config: cfg50 },
  { Comp: Shot51 as React.FC, config: cfg51 },
  { Comp: Shot52 as React.FC, config: cfg52 },
  { Comp: Shot53 as React.FC, config: cfg53 },
  { Comp: Shot54 as React.FC, config: cfg54 },
  { Comp: Shot55 as React.FC, config: cfg55 },
  { Comp: Shot56 as React.FC, config: cfg56, defaultProps: dp56, calculateMetadata: cm56 },
  { Comp: Shot57 as React.FC, config: cfg57 },
];
