// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים קָמָץ!', start: 0.0, end: 4.776, words: [] },
  { text: 'בָּ', start: 5.0, end: 5.58, words: [], units: [{ g: 'בָּ', start: 5.3, end: 5.58 }] },
  { text: 'בָּ מָּ קָּ', start: 11.0, end: 13.98, words: [], units: [{ g: 'בָּ', start: 11.3, end: 11.58 }, { g: 'מָּ', start: 12.43, end: 12.73 }, { g: 'קָּ', start: 13.72, end: 13.98 }] },
  { text: 'בָּבָּא', start: 19.0, end: 22.552, words: [], units: [{ g: 'בָּ', start: 19.3, end: 19.58 }, { g: 'בָּא', start: 21.076, end: 21.376 }] },
  { text: 'בָּבָּא!', start: 28.0, end: 29.848, words: [] },
  { text: 'אַתֶּם! הִמְהוּם…', start: 33.0, end: 37.104, words: [] },
];
