// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים שׁוּרוּק! הַצְּלִיל "אוּ"!', start: 0.0, end: 7.008, words: [] },
  { text: 'וּ', start: 8.033, end: 8.513, words: [], units: [{ g: 'וּ', start: 8.333, end: 8.513 }] },
  { text: 'בּוּ גּוּ לוּ מוּ', start: 10.233, end: 14.563, words: [], units: [{ g: 'בּוּ', start: 10.533, end: 10.873 }, { g: 'גּוּ', start: 11.743, end: 12.183 }, { g: 'לוּ', start: 13.073, end: 13.373 }, { g: 'מוּ', start: 14.223, end: 14.563 }] },
  { text: 'סוּס', start: 16.033, end: 18.073, words: [], units: [{ g: 'סוּס', start: 16.373, end: 16.953 }] },
  { text: 'סוּס!', start: 20.033, end: 22.097, words: [] },
  { text: 'אַתֶּם!', start: 23.366, end: 25.478, words: [] },
];
