// AUTO-GENERATED by tools/gen_voice_reading.py — do not edit.
// Word/unit times are REAL trimmed edge-tts clip bounds; sub-word highlight syncs exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'בּוּ בּוּ! הַיּוֹם לוֹמְדִים צֵירֵי! הַצְּלִיל "אֵי"!', start: 0.0, end: 7.176, words: [] },
  { text: 'בֵּ', start: 8.033, end: 8.653, words: [], units: [{ g: 'בֵּ', start: 8.333, end: 8.653 }] },
  { text: 'בֵּ מֵ לֵ שֵׁ', start: 10.233, end: 14.443, words: [], units: [{ g: 'בֵּ', start: 10.533, end: 10.853 }, { g: 'מֵ', start: 11.723, end: 12.043 }, { g: 'לֵ', start: 12.933, end: 13.213 }, { g: 'שֵׁ', start: 14.143, end: 14.443 }] },
  { text: 'דֶּלֶת', start: 16.033, end: 19.969, words: [], units: [{ g: 'דֶּ', start: 16.333, end: 16.793 }, { g: 'לֶת', start: 18.317, end: 18.577 }] },
  { text: 'דֶּלֶת!', start: 22.033, end: 24.217, words: [] },
  { text: 'אַתֶּם!', start: 25.366, end: 27.478, words: [] },
];
